### ISSUE TITLE
Factor Kurve types / references out of Office.tsx - okay to leave Kurve Data Model types

### ISSUE THREAD

**Issue by johnshew** [johnshew/GraphDashboard#16]
Should be a pure Office React project.  

App.tsx can use Kurve to load Graph data objects that are used by the Office react components.

**Comment by billba** [comment]
The way to think about this is that Kurve and OfficeReact both share the Graph data model. But OfficeReact should be agnostic as to where its data is coming from.

**Comment by johnshew** [comment]
Agree.  That is great point... so saying ALL is a little strong... we can use the Kurve data model classes - that directly correspond to the graph but we shouldn't use the Kurve classes that are responsible for the protocol implemention.

**Comment by billba** [comment]
fixed https://github.com/johnshew/GraphDashboard/commit/d64b99c8ea1be2d5ef0fc09e0b66a363b9dca5fb
