### ISSUE TITLE
message list width jumps around depending on window size

### ISSUE THREAD

**Issue by billba** [johnshew/GraphDashboard#19]
1. Run the app, login
2. Resize the window, making it narrower and wider

Expect: message list to either have a fixed width, or a minimum width that expands with the window width
Result: width goes through a number of gyrations

**Comment by billba** [comment]
Bootstrap settings just needs some refinement here. They're overly aggressive in terms of what is considered "medium" and "small".

**Comment by johnshew** [comment]
Should be better now.  @billba can you check and close?

**Comment by billba** [comment]
Better. I'd call this above the bar for the Alpha.
