### ISSUE TITLE
Should bundle.js be included in repository?

### ISSUE THREAD

**Issue by billba** [johnshew/GraphDashboard#4]
It's a compiled file. Seems like it would be better to force folks to generate it using **npm bulld**.

**Comment by billba** [comment]
Ditto typings/react/\* which are fetched by **npm typings**

**Comment by billba** [comment]
Upon reflection, I think bundle.js should _not_ be in the repo, but eventually we'll have a compiled/minified/etc. distribution that will be.

**Comment by johnshew** [comment]
Agree on long-term.  But in the short-term it is necessary as the app on gh-pages won't run without it.
